[package]
name = "crust-prototype"
version = "0.1.0"
authors = ["Omar Jair Purata Funes <omarpurataf@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
libc = "0"

[build-dependencies]
gcc = "0"
